### ISSUE TITLE
Change from Vertical to Horizontal Menu

### ISSUE THREAD

**Issue by f0nZ** [ppizarror/python-pygame-menu#1]
Hi there, I'm a python newb and have been looking for quite some time on how to make an Horizontal Menu. I noticed for instance you use .append to add menu itens, is there any way to do the same but horizontally?

Kind regards.

**Comment by ppizarror** [comment]
Hi, check https://github.com/ppizarror/pygame-menu, it's a newer version.
I have not implemented position of elements, but it's a great idea!!, i will work on that soon
